apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # TODO:
  # console.config.openshift.io (?) -> look @ Adam K's build  in
  # openshift controller manager repo, or talk to Adam K/Ben Parees
  # TODO:
  # David has defined some naming rules on this, a few restrictions
  # to ensure it is correct
  name: consoles.console.openshift.io
spec:
  # TODO:
  # soon config.openshift.io
  group: console.openshift.io
  names:
    kind: Console
    listKind: ConsoleList
    plural: consoles
    singular: console
  # TODO:
  # soon will be cluster scoped
  scope: Namespaced
  version: v1alpha1
  # TODO: will need to regen code after moving this
  # because all my clients will no longer work.
  # - change magic comments from "namespaced" to "not namespaced"
  # go find // +genclient on other cluster scoped resources like
  # the oauthclient:
  #  // +genclient
  #  // +genclient:nonNamespaced

