# console config is the public facing configuration
# of the console
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoles.config.openshift.io
spec:
  scope: Cluster
  group: config.openshift.io
  version: v1
  names:
    kind: Console
    listKind: ConsoleList
    plural: consoles
    singular: console
  subresources:
    status: {}
