apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoles.operator.openshift.io
spec:
  scope: Cluster
  group: operator.openshift.io
  names:
    kind: Console
    listKind: ConsoleList
    plural: consoles
    singular: console
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            managementState:
              pattern: ^(Managed|Unmanaged|Removed|Forced)$
              type: string
              description: ManagementState indicates whether and how the operator
                should manage the component
            customization:
              properties:
                documentationBaseURL:
                  pattern: ^$|^((https):\/\/?)[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:]\s]|\/?))\/$
                  type: string
                  description: Documentation base url can optionally be set but must
                    end in a trailing slash
                brand:
                  pattern: ^$|^(ocp|origin|okd|dedicated|online|azure)$
                  type: string
                  description: Brand may be optionally set to one of six values -
                    azure|dedicated|ocp|okd|online|origin
            providers:
              properties:
                statuspage:
                  properties:
                    pageID:
                      type: string
                      description: Contains ID for statuspage.io page that provides
                        status info about.
