# TODO: This CRD will be eliminated in favor of:
# https://github.com/openshift/cluster-config-operator/pull/11
# console config is the public facing configuration
# of the console
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoles.config.openshift.io
spec:
  scope: Cluster
  group: config.openshift.io
  names:
    kind: Console
    listKind: ConsoleList
    plural: consoles
    singular: console
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
