apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-operator
  namespace: openshift-console-operator
  labels:
    name: console-operator
  annotations:
    config.openshift.io/inject-proxy: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: console-operator
  template:
    metadata:
      labels:
        name: console-operator
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      priorityClassName: system-cluster-critical
      serviceAccountName: console-operator
      containers:
      - name: console-operator
        terminationMessagePolicy: FallbackToLogsOnError
        image: registry.svc.ci.openshift.org/openshift:console-operator
        ports:
        - containerPort: 60000
          name: metrics
        command:
        - console
        - operator
        args:
        - |
          if [ -s /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt ]; then
              echo "Copying system trust bundle"
              cp -f /var/run/configmaps/trusted-ca-bundle/ca-bundle.crt /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          fi
          exec console-operator operator --config=/var/run/configmaps/config/controller-config.yaml --v=2 --terminate-on-files=/var/run/configmaps/trusted-ca-bundle/ca-bundle.crt
        # args:
        # - "-v=2"
        # - "--config=/var/run/configmaps/config/controller-config.yaml"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
        - mountPath: /var/run/configmaps/trusted-ca-bundle
          name: trusted-ca-bundle
          readOnly: true
        env:
        - name: IMAGE
          value: registry.svc.ci.openshift.org/openshift:console
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        - name: OPERATOR_NAME
          value: "console-operator"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
      volumes:
      - name: config
        configMap:
          name: console-operator-config
      - name: serving-cert
        secret:
          secretName: serving-cert
          optional: true
      - name: trusted-ca-bundle
        configMap:
          name: trusted-ca-bundle
          optional: true
