kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-console-operator
  namespace: openshift-console
subjects:
- kind: ServiceAccount
  name: console-operator
  namespace: openshift-console
roleRef:
  kind: Role
  name: console-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: console-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-operator
subjects:
- kind: ServiceAccount
  name: console-operator
  namespace: openshift-console