apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  managementState: Managed
  unsupportedConfigOverrides:
    auth:
      clientID: samwisegamgee
      logoutRedirect: https://samwisegamgee.com/you-re-nowt-but-a-ninnyhammer-Sam-Gamgee
    customization:
      branding: samwisegamgee

