apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoleclidownloads.console.openshift.io
  annotations:
    displayName: ConsoleCLIDownload
    description: Extension for configuring openshift web console command line interface (CLI) downloads.
spec:
  scope: Cluster
  group: console.openshift.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    plural: consoleclidownloads
    singular: consoleclidownload
    kind: ConsoleCLIDownload
    listKind: ConsoleCLIDownloadList
  additionalPrinterColumns:
    - name: Display name
      type: string
      JSONPath: .spec.displayName
    - name: Age
      type: string
      JSONPath: .metadata.creationTimestamp
    - name: Description
      type: string
      JSONPath: .spec.description
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console CLI download spec
          required:
            - displayName
            - description
            - links
          properties:
            displayName:
              type: string
              description: Display name of the CLI download
            description:
              type: string
              description: Description of the CLI download (can include markdown)
            links:
              type: array
              description: Objects that hold CLI download link details
              nullable: true
              items:
                type: object
                required:
                  - href
                properties:
                  text:
                    type: string
                    description: Text of the link
                  href:
                    type: string
                    description: Absolute secure URL for the link (must use https)
                    pattern: '^https://([\w-]+.)+[\w-]+(/[\w- ./?%&=])?$'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consolelinks.console.openshift.io
  annotations:
    displayName: ConsoleLinks
    description: Extension for customizing OpenShift web console links
spec:
  scope: Cluster
  group: console.openshift.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    plural: consolelinks
    singular: consolelink
    kind: ConsoleLink
    listKind: ConsoleLinkList
  additionalPrinterColumns:
    - name: Text
      type: string
      JSONPath: .spec.text
    - name: URL
      type: string
      JSONPath: .spec.href
    - name: Menu
      type: string
      JSONPath: .spec.menu
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console link customizations spec
          required:
            - text
            - href
            - location
          properties:
            text:
              type: string
              description: Text of the link
            href:
              type: string
              description: Absolute secure URL for the link (must use https)
              pattern: '^https://([\w-]+.)+[\w-]+(/[\w- ./?%&=])?$'
            location:
              type: string
              description: Determines which dropdown menu the link is added to (HelpMenu, UserMenu)
              pattern: '\bHelpMenu\b|\bUserMenu\b'
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consolenotifications.console.openshift.io
  annotations:
    displayName: ConsoleNotification
    description: Extension for configuring openshift web console notifications.
spec:
  scope: Cluster
  group: console.openshift.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    plural: consolenotifications
    singular: consolenotification
    kind: ConsoleNotification
    listKind: ConsoleNotificationList
  additionalPrinterColumns:
    - name: Text
      type: string
      JSONPath: .spec.text
    - name: Location
      type: string
      JSONPath: .spec.location
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          description: Represents console notification spec
          required:
            - text
            - location
          properties:
            text:
              type: string
              description: Text of the notification
            location:
              type: string
              description: The location of the notification (BannerTop, BannerBottom, BannerTopBottom)
              pattern: '\bBannerTop\b|\bBannerBottom\b|\bBannerTopBottom\b'
            link:
              type: object
              description: Object that holds notification link details
              required:
                - href
                - text
              properties:
                text:
                  type: string
                  description: Text of the link
                href:
                  type: string
                  description: Absolute secure URL for the link (must use https)
                  pattern: '^https://([\w-]+.)+[\w-]+(/[\w- ./?%&=])?$'
            backgroundColor:
              type: string
              description:  The background color for the notification as CSS data type color
            color:
              type: string
              description:  The color of the text for the notification as CSS data type color
