# the canonical version lives at:
# https://github.com/openshift/cluster-config-operator/blob/master/manifests/0000_05_config-operator_01_console.crd.yaml
# this is a copy for dev purposes...
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoles.config.openshift.io
spec:
  scope: Cluster
  group: config.openshift.io
  names:
    kind: Console
    listKind: ConsoleList
    plural: consoles
    singular: console
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true


